### ISSUE TITLE
Autocorrection with standardrb --fix

### ISSUE THREAD

**Issue by JoshTGreenwood** [andrewmcodes/standardrb-action#7]
Thanks for creating this action, we have already found it very helpful!

I was thinking about how we could ease the transition to standard inside of my organization, and I think automatically fixing fixable issues would be a huge productivity boost and cause folks to get excited to switch. In that vein, have you considered using the `standardrb --fix` mode within the action? 

Here's how I was thinking it might work:
1. allow a new configuration flag to opt into this behavior
2. run `standardrb --fix` instead of `standard`
3. create a commit on the branch with a message like "standardrb fixes". [here is an example of something similiar](https://github.com/stefanzweifel/git-auto-commit-action).
4. continue to report on non-fixable issues as we do today.

What do you think?

Feel free to close this issue if there's a more appropriate venue to discuss this idea.

**Comment by andrewmcodes** [comment]
@JoshTGreenwood sorry, I somehow missed this notification. I have considered this, and have even proofed out that the concept would work. I have made a lot of changes to the [rubocop action](https://github.com/andrewmcodes/rubocop-linter-action) that this one was based on and there are some changes in the latest v3 release candidate that I need to port over before considering adding the auto correct. 

If it's something you're interested in, I would be willing to add it. I initially added it for rubocop but backed out since the release was already a huge change and there are some issues with committing from actions that I was spending too long on, but the only one I had left wouldn't stop the ability to ship that feature.

**Comment by andrewmcodes** [comment]
I don't think this belongs inside this action anymore. This action exists specifically to integrate Standard and GitHub checks into an easy to use action. 

If you are still interested in this I'd suggest just doing this with bash in your action if this action is successful.
